---
title: "Gov 50 Final Project"
author: "Karen Torres"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts (Milestone 1)

I am interested in exploring data related to the Latino Vote. I am currently a fellow for Voto Latino and they do a lot of research on the Latino vote. I think it would be really cool to do my final project on the Latino vote while working with Voto Latino. Voto Latino will be an excellent resource for this project. I will probably focus on voter suppression or misinformation. I look forward to be able to do my project on a topic I am so passionate about. 

## Project Proposal for Data Set (Milestone 2)

Why are Latinos voters in the battleground states in 2022 supporting passing a federal law to protect abortion access after historically being for the most part, against protecting abortion access? To answer this research question, I will be using the October Latino Battleground Survey Results from Voto Latino. When it comes to my hypothesis,  I believe that Latinos are more likely to support passing a federal law to protect abortion because the Latino population in the United States is both largely young and democrat. A Pew Research Center study found that nearly half of U.S.-born Latinos are younger than 18. With the majority of the Latino voting population being so young, I do expect them to be in favor of passing a law that protects women’s reproductive rights. Additionally, Voto Latino’s data found that Democrats have a trust advantage with Latino voters. In this study, I plan to examine what kind of  Latino voters were more likely to support abortion access. I would be specifically looking at age and party. The explanatory variables of interest are whether the voter was young or not young and then democrat or republican. The variable is coded =1 if they are under 18 and =0 if above 18. The same would be true for whether they are Democrats or Republicans. My outcome variable would be the count of voters who supported abortion rights that were young and democratic. I would measure this by probably getting the average and seeing what percentage of the Latino voters were young and democratic. If the percentage was higher than 50 percent, it would prove my hypothesis. If the percentage is lower, then it means I was wrong and that the majority of the supporters were not young democrats and that perhaps age and party do not have a relation with whether the voter supports abortion access or not. 


